### ISSUE TITLE
vmysql 数据库监控工具

### ISSUE THREAD

**Issue by rockmelodies** [virink/vMysqlMonitoring#2]
vmysql数据库监控工具 没有

**Comment by mozhu1024** [comment]
@rockmelodies ？？？

**Comment by Bre3Ze** [comment]
师傅 想问一下c#的是怎么编译的

**Comment by mozhu1024** [comment]
@Bre3Ze Visual Studio 2015 直接编译啊

**Comment by Bre3Ze** [comment]
谢谢Virink师傅   昨天直接用.netframework自带的csc.exe编译除了问题，不过我已经找到了你编译好的版本

**Comment by mozhu1024** [comment]
@Bre3Ze 讲真、、不用 win 好久了、、都不维护 win 版本的、、最新功能都在 osx。。。
