### ISSUE TITLE
咋部署啊，对萌新友好一点啊

### ISSUE THREAD

**Issue by FuGitHub0** [virink/vMysqlMonitoring#4]
大哥你说一下咋部署使用啊，太不友好了

**Comment by mozhu1024** [comment]
我忘了

**Comment by FuGitHub0** [comment]
> 我忘了

卧槽无情！！

**Comment by mozhu1024** [comment]
> > 我忘了
> 
> 卧槽无情！！

这都多久的项目了。。。反正我早就忘了、、挖坑，不管埋

**Comment by FuGitHub0** [comment]
我枯了……------------------ 原始邮件 ------------------
发件人: "Virink"<notifications@github.com>
发送时间: 2020年3月3日(星期二) 凌晨0:02
收件人: "virink/vMysqlMonitoring"<vMysqlMonitoring@noreply.github.com>;
抄送: "FuGitHub0"<1635829940@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [virink/vMysqlMonitoring] 咋部署啊，对萌新友好一点啊 (#4)


  
我忘了
  
卧槽无情！！
  
这都多久的项目了。。。反正我早就忘了、、挖坑，不管埋
 
&mdash;
